server:
  port: 0

mybatis:
  # 注册mybatis中实体类的别名
  type-aliases-package: luffy.test.bean
  # 注册映射文件
  mapper-locations: classpath:mapper/*.xml

spring:
  # 注册数据源
  datasource:
    # 指定数据源类型为Druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///ssm?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password:

  # 连接Redis服务器
#  redis:
#    host: redis5OS
#    port: 6379
#    password: 111

  # 连接Redis高可有集群
  #  redis:
  #    sentinel:
  #      master: mymaster
  #      nodes:
  #        - sentinelOS1:26379
  #        - sentinelOS2:26379
  #        - sentinelOS3:26379

  # 配置缓存
#  cache:
#    type: redis # 指定缓存类型
#    cache-names: realTimeCache   # 指定缓存区域名称

  # 功能等价于spring-dubbo配置文件中的<dubbo:application/>
  # 该名称是由服务治理平台使用
  application:
    name: springboot-provider
  # 指定zk注册中心
  dubbo:
#    registry: zookeeper://hadoop01:2181?backup=hadoop02:2181
    registry: zookeeper://localhost:2181
  # zk集群作注册中心
  # registry: zookeeper://zkOS1:2181?backup=zkOS2:2181,zkOS3:2181

